name: Auto Releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # does checkouts whatever those are
      - uses: actions/checkout@v4

      # remove unused software
      - name: read run smh
        run: |
          sudo apt remove firefox php8.3* 
          

      # update & upgrade
      - name: read run smh
        run: |
          sudo apt update && sudo apt upgrade
          

      - name: download dependencys
        run: |
          sudo apt-get install -y build-essential libsdl2-dev libgl-dev libglu1-mesa-dev libpthread-stubs0-dev meson
          
          
      - name: clone 4jcraft
        run: |
          git clone https://github.com/4jcraft/4jcraft.git

      - name: cd
        run: |
          ls
          cd 4jcraft
          

      - name: do build dir with meson
        run: |
          meson setup build
          

      - name: now do compily compily
        run: | 
          meson compile -C build
